name: Release

on:
  push:
    tags:
    - '*'

jobs:

  build:
    name: Release
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Get tag
      id: get_version
      run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build
      env:
        CGO_ENABLED: 0
      run: go build -ldflags="-s -w"

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: go-werk-${{ steps.get_version.outputs.SOURCE_TAG }}
        # A file, directory or wildcard pattern that describes what to upload
        path: /home/runner/work/go-werk/go-werk/go-werk